#!/bin/bash
#
# NAME
# wp-cdtc - Bash script to change charset and collate to database specific tables. Reads the config data from wp-config.php
#
# DESCRIPTION
# This script read wp-config.php file, create a backup and convert the collate and charset to all tables setted into tables.txt file
#
# USAGE
#	wp-cdtc /path/to/tables.txt utf8mb4 utf8mb4_unicode_520_ci
#
# INSTALLATION
# - `sudo chmod +x /path/to/wordpress-change-database-table-collate/wp-cdtc`
# - `ln -s /path/to/wordpress-change-database-table-collate/wp-cdtc /usr/local/bin/wp-cdtc`
# - `mv tables.txt.example tables.txt`
# - set all tables (each for line) into tables.txt
#
# AUTHOR:
#	wp-cdtc is written by Alfio Salanitri <www.alfiosalanitri.it> and are licensed under the MIT License.

#############################################################
# get config value from wp-config file
function get_config_value() {
  find . -type f -name wp-config.php -exec cat {} \; | grep $1 | awk '{print $3};' | sed "s/'//g;s/\;//g"
}

#############################################################
readonly DB_NAME=$(get_config_value DB_NAME)
readonly TABLE_PREFIX=$(get_config_value table_prefix)

if [ ! -f "$1" ]; then
  echo "[!] Type the full path to tables.txt file with database tables name (each for line)."
  exit 1
fi

if [ -z "$2" ]; then
  echo "[!] Type the charset (es: utf8mb4)."
  exit 1
fi
if [ -z "$3" ]; then
  echo "[!] Type the collate (es: utf8mb4_unicode_520_ci)."
  exit 1
fi
if [ "" == "$DB_NAME" ] || [ "" == "$TABLE_PREFIX" ]; then
  echo "[!] db_name or table_prefix not found in wp-config.php"
  exit 1
fi

# set charset and collate
readonly CHARSET=$2
readonly COLLATE=$3
# create array from txt file
mapfile -t DB_TABLES < $1

echo "[1/2] backup database, wait please..."
if [ "" != "$(mysqldump $DB_NAME > $DB_NAME-bkp.sql)" ]; then
  echo "[!] backup database failed!"
  exit 1
fi

echo "[2/2] update database tables, wait please..."
for TABLE in ${DB_TABLES[@]};
do
  result=$(mysql --database=$DB_NAME -e "ALTER TABLE \`${TABLE_PREFIX}$TABLE\` CONVERT TO CHARACTER SET $CHARSET COLLATE $COLLATE;" 2>&1 )
  if [ $? != 0 ]; then
   echo "[!] alter failed for $TABLE: $result"
   exit 1
  fi
  echo "-- $TABLE updated."
done
echo "[ok] conversion completed."
exit 0